
POST http://192.168.1.16:3002/
Content-Type: application/json

{
      "pageNumber":1,
      "perPage":3,
      "groups": {
          "admin": {
            "pageNumber":4,
            "perPage":2
          },
          "superAdmin": {
            "pageNumber":1,
            "perPage":2
          }
      }
}