//Get all users
GET https://tranquil-cliffs-32037.herokuapp.com/

###
//Get users without grouping
POST https://tranquil-cliffs-32037.herokuapp.com/
Content-Type: application/json

{
      "pageNumber":1,
      "perPage":3
}

###
//Get users with grouping
POST https://tranquil-cliffs-32037.herokuapp.com/
Content-Type: application/json

{
      "groups": {
          "admin": {
            "pageNumber":4,
            "perPage":2
          },
          "superAdmin": {
            "pageNumber":2,
            "perPage":2
          },
           "fan":{
            "pageNumber":1,
            "perPage":2
          },
          "creator":{
            "pageNumber":1,
            "perPage":2
          }
      }
}